services:

  nodered:
    image: sheng2216/nodered-docker:alpine-latest
    container_name: NodeRed
    user: node-red
    group_add:
      - 998
    restart: unless-stopped
    environment:
        - NODE_RED_ENABLE_PROJECTS=${NODE_RED_ENABLE_PROJECTS}
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=${TZ}
    volumes:
        - '/node_red_data:/data'
    ports:
        - "1880:1880/tcp"
    devices:
        - "/dev/i2c-1:/dev/i2c-1"
        
