version: '3.7'

services:

  nodered:
    image: sheng2216/nodered-docker:1.1
    container_name: NodeRed
    user: node-red
    group_add:
        - 997
    restart: unless-stopped
    environment:
        - NODE_RED_ENABLE_PROJECTS=false
        - PUID=1000
        - PGID=100
        - TZ=Europe/London
    devices:
        - "/dev/gpiochip0:/dev/gpiochip0"
    volumes:
        - 'node-red-data:/data'
    ports:
        - "1880:1880/tcp"
    networks:
        - node-red
volumes:
  node-red-data:

networks:
  node-red: